added makefile
biomage-ltd/pipeline pull request #42
Opened 2021-04-16 12:23 UTC by kafkasl

Added Makefile for convenience

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [x] Relevant Github READMEs updated
- [x] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [X] Photo of a cute animal attached to this PR

![image](https://user-images.githubusercontent.com/2961095/115021785-bb660e00-9ebc-11eb-8cce-b8d6e4908238.png)

2021-04-16 12:25 UTC, kafkasl commented
@ogibson-biomage @alexvpickering if I understood correctly you are the only ones using linux. Using `make run` should no longer need `export DOCKER_GATEWAY_HOST=`docker network inspect --format='{{range .IPAM.Config}}{{.Gateway}}{{end}}'` to work on Linux but I haven't tested it. Could either of you try to `make build && make run`  and see if it works without that enviroment variable set?

2021-04-16 13:34 UTC, xverges requested changes

2021-04-16 15:01 UTC, kafkasl commented on Makefile
> +	@(cd ./local-runner && npm install)
I have seen `npm install` in all the readmes. Should I update them all? Or why it's been using `npm install` everywhere.

2021-04-16 15:07 UTC, kafkasl commented on Makefile
> +	export DOCKER_GATEWAY_HOST=`docker network inspect --format='{{range .IPAM.Config}}{{.Gateway}}{{end}}'
fixed

2021-04-19 23:43 UTC, alexvpickering commented
> @ogibson-biomage @alexvpickering if I understood correctly you are the only ones using linux. Using `make run` should no longer need
> 
> ```
> export DOCKER_GATEWAY_HOST=`docker network inspect --format='{{range .IPAM.Config}}{{.Gateway}}{{end}}'
> ```
> 
> to work on Linux but I haven't tested it. Could either of you try to `make build && make run` and see if it works without that enviroment variable set?

Tested `make build && make run`  locally and it worked with caveats:

1) I still have to change `'host.docker.internal'` on line 250 in `init.r` to `'192.168.0.117'` which is the result of `hostname -I |awk '{print $1}'`
2) 
```
DOCKER_GATEWAY_HOST=`docker network inspect --format='{{range .IPAM.Config}}{{.Gateway}}{{end}}'`
```
 doesn't do anything on my linux box:

![image](https://user-images.githubusercontent.com/15719520/115315991-4baa8a00-a12d-11eb-9241-468b29b57a53.png)

3) Are missing a backtick at the end of the above env variable declaration?

2021-04-21 11:51 UTC, kafkasl commented
@alexvpickering Thanks for testing, some questions
> Tested `make build && make run` locally and it worked with caveats:
> 
> 1. I still have to change `'host.docker.internal'` on line 250 and `development_aws_server` on line 24 in `init.r` to `'192.168.0.117'` which is the result of `hostname -I |awk '{print $1}'`

Line 250 of which file? 

> ```
> DOCKER_GATEWAY_HOST=`docker network inspect --format='{{range .IPAM.Config}}{{.Gateway}}{{end}}'`
> ```
> 
> doesn't do anything on my linux box:
> 
> ![image](https://user-images.githubusercontent.com/15719520/115315991-4baa8a00-a12d-11eb-9241-468b29b57a53.png)
> 
> 1. Are you missing a backtick at the end of the above env variable declaration?

Yes, there was a missing backtick, however the point was that exporting that variable was no longer needed, so it doesn't matter.

2021-04-22 16:13 UTC, ivababukova reviewed
have you tested it with a linux user?

2021-04-22 16:27 UTC, alexvpickering commented
line 250 of `init.r` in pipeline

2021-04-22 16:29 UTC, alexvpickering commented
> 1. I still have to change `'host.docker.internal'` on line 250 and `development_aws_server` on line 24 in `init.r` to `'192.168.0.117'` which is the result of `hostname -I |awk '{print $1}'`

both line 250 and 24 or `init.r` in pipeline

2021-04-23 21:36 UTC, alexvpickering commented
Thanks @kafkasl looks good to me! I removed the docker stuff from the README

2021-04-26 08:04 UTC, xverges approved these changes

2021-04-26 08:05 UTC, merged